ProjectWeb-20200327T074237Z-001/ProjectWeb/src/java/model/CarTBLDB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static model.Databaseinfo.dbURL;
import static model.Databaseinfo.driverName;
import static model.Databaseinfo.passDB;
import static model.Databaseinfo.userDB;

/**
 *
 * @author letan
 */
public class CarTBLDB implements Databaseinfo{

 public  boolean addNewCar(int uid,String bienso, int socho,int tienchothue, String hangxe,String nguyenlieu,String hopso,int tiendatcoc,String noiohientai,String mota,String tinhnangxe,String imgxe,String imgCV){
        try {
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL,userDB,passDB);
            PreparedStatement stmt= con.prepareStatement("insert into CarTBL(uid,bienso,socho,tienchothue,hangxe,loainguyenlieu,hopso,tiencoc,noiohientai,mota,tinhnangxe,imgxe,imgCV) values"
                    + "("+uid+",'"+bienso+"',"+socho+","+tienchothue+",'"+hangxe+"',N'"+nguyenlieu+"',N'"+hopso+"',"+tiendatcoc+",N'"+noiohientai+"',N'"+mota+"',N'"+tinhnangxe+"','"+imgxe+"','"+imgCV+"')");
            stmt.executeUpdate();
            con.close();
        } catch (Exception ex) {
            Logger.getLogger(UserTBLDB.class.getName()).log(Level.SEVERE, null, ex);
          return false;
        }
           return true;
    }
         public  int getbienso(String bienso){
        int uid=0;
        try {
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL,userDB,passDB);
            PreparedStatement stmt= con.prepareStatement("select uid from CarTBL where bienso='"+bienso+"'");
            ResultSet rs = stmt.executeQuery();
             while(rs.next()){
                 uid = rs.getInt(1);
             }
             con.close();
        } catch (Exception ex) {
            Logger.getLogger(UserTBLDB.class.getName()).log(Level.SEVERE, null, ex);
        }
        return uid;
    }
         public ArrayList<CarTBL> getAllbystatusAcceptCar() {
        ArrayList<CarTBL> list = new ArrayList<>();
        try {
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL, userDB, passDB);
            PreparedStatement stmt = con.prepareStatement("Select bienso,socho,hangxe,loainguyenlieu,hopso,noiohientai,status,tinhnangxe,tienchothue,statusAccepted from CarTBL where statusAccepted ='Unaccepted'");
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                String bienso = rs.getString(1);
                int socho = rs.getInt(2);
                String hangxe = rs.getString(3);
                String loainguyenlieu = rs.getString(4);
                String hopso = rs.getString(5);
                String noiohientai = rs.getString(6);
                String status = rs.getString(7);
                String tinhnangxe = rs.getString(8);
                int tienchothue = rs.getInt(9);
                String statusAccepted = rs.getString(10);
                list.add(new CarTBL(bienso, socho, hangxe, loainguyenlieu, hopso, noiohientai, status, tinhnangxe, tienchothue, statusAccepted));
            }
            con.close();
        } catch (Exception ex) {
            Logger.getLogger(CarTBL.class.getName()).log(Level.SEVERE, null, ex);
        }
        return list;
    }
    public CarTBL acceptStatusCar(String bienso) {
        try {
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL, userDB, passDB);
            PreparedStatement stmt = con.prepareStatement("Update CarTBL set statusAccepted = 'Accepted' where bienso = '" + bienso + "'");
            int rs = stmt.executeUpdate();
            con.close();
        } catch (Exception ex) {
            Logger.getLogger(CarTBL.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
     public CarTBL unAcceptStatusCar(String bienso) {
        try {
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL, userDB, passDB);
            PreparedStatement stmt = con.prepareStatement("Update CarTBL set statusAccepted = 'Cancel' where bienso = '" + bienso + "'");
            int rs = stmt.executeUpdate();
            con.close();
        } catch (Exception ex) {
            Logger.getLogger(CarTBL.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    public static void main(String[] args) {
       CarTBLDB st = new CarTBLDB();
//       st.getbienso("92G1-19927");
           st.addNewCar(1,"92G1-19928",4, 1000000,"toyota 2019","Xăng", "tự động", 15000000, "Đà Nẵng", "Xe vip nhất Sài Gòn","Cửa Trần","test","abc");
}}

ProjectWeb-20200327T074237Z-001/ProjectWeb/src/java/model/OrderTBL.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static model.Databaseinfo.dbURL;
import static model.Databaseinfo.driverName;
import static model.Databaseinfo.passDB;
import static model.Databaseinfo.userDB;

/**
 *
 * @author letan
 */
public class OrderTBL extends CarTBL implements Databaseinfo {

    private int oid;
    private int Hirecarid;
    private int tiencoc;
    private String ngaynhan;
    private String ngaytra;
    private String ghichu;
    private double tongtien;
    private double tienchuxe;
    private double fee;
    private String statusorder;

    public OrderTBL() {
    }

    public OrderTBL(int tongtien, String statusorder) {
        this.tongtien = tongtien;
        this.statusorder = statusorder;
    }

    public OrderTBL(String statusorder, int Hirecarid) {
        this.Hirecarid = Hirecarid;
        this.statusorder = statusorder;
    }

    public OrderTBL(int Hirecarid, double tongtien) {
        this.Hirecarid = Hirecarid;
        this.tongtien = tongtien;
    }

    public OrderTBL(int Hirecarid, double tongtien, double tienchuxe, double fee) {
        this.Hirecarid = Hirecarid;
        this.tongtien = tongtien;
        this.tienchuxe = tienchuxe;
        this.fee = fee;
    }

    public OrderTBL(int uid, String name, String phonenb, String bienso, String ngaynhan, String ngaytra, int tongtien) {
        super(uid, name, phonenb, bienso);
        this.ngaynhan = ngaynhan;
        this.ngaytra = ngaytra;
        this.tongtien = tongtien;
    }

    public String getStatusorder() {
        return statusorder;
    }

    public void setStatusorder(String statusorder) {
        this.statusorder = statusorder;
    }

//    public OrderTBL(int uid,int phonenb,int,int oid, int Hirecarid, Date startrent, Date endrent, int tiencoc, Date ngaynhan, Date ngaytra, String ghichu, int tongtien) {
//        
//        super(uid);
//        this.oid = oid;
//        this.Hirecarid = Hirecarid;
//        this.startrent = startrent;
//        this.endrent = endrent;
//        this.tiencoc = tiencoc;
//        this.ngaynhan = ngaynhan;
//        this.ngaytra = ngaytra;
//        this.ghichu = ghichu;
//        this.tongtien = tongtien;
//    }
    public int getOid() {
        return oid;
    }

    public void setOid(int oid) {
        this.oid = oid;
    }

    public int getHirecarid() {
        return Hirecarid;
    }

    public void setHirecarid(int Hirecarid) {
        this.Hirecarid = Hirecarid;
    }

    public int getTiencoc() {
        return tiencoc;
    }

    public void setTiencoc(int tiencoc) {
        this.tiencoc = tiencoc;
    }

    public String getNgaynhan() {
        return ngaynhan;
    }

    public void setNgaynhan(String ngaynhan) {
        this.ngaynhan = ngaynhan;
    }

    public String getNgaytra() {
        return ngaytra;
    }

    public void setNgaytra(String ngaytra) {
        this.ngaytra = ngaytra;
    }

    public String getGhichu() {
        return ghichu;
    }

    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    public void setFee(int fee) {
        this.fee = fee;
    }

    public double getTongtien() {
        return tongtien;
    }

    public void setTongtien(double tongtien) {
        this.tongtien = tongtien;
    }

    public double getTienchuxe() {
        return tienchuxe;
    }

    public void setTienchuxe(double tienchuxe) {
        this.tienchuxe = tienchuxe;
    }

    public double getFee() {
        return fee;
    }

    public void setFee(double fee) {
        this.fee = fee;
    }

    public void setTienchuxe(int tienchuxe) {
        this.tienchuxe = tienchuxe;
    }

    public OrderTBL(String statusorder) {
        this.statusorder = statusorder;
    }

    @Override
    public String toString() {
        return "OrderTBL{" + "statusorder=" + statusorder + '}';
    }

    public ArrayList<OrderTBL> checksttOrder(int id) { // userID
        ArrayList<OrderTBL> c = new ArrayList<>();
        try {
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL, userDB, passDB);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select status,Hirecarid from OrderTBL where uid='" + id + "'");
            while (rs.next()) {
                c.add(new OrderTBL(rs.getString(1), rs.getInt(2)));
            }
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return c;
    }

    public ArrayList<OrderTBL> getinfomationOrder(int id) { // userID
        ArrayList<OrderTBL> c = new ArrayList<>();
        try {
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL, userDB, passDB);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select HirecarTBL.Hirecarid,OrderTBL.tongtien from HirecarTBL inner join OrderTBL on HirecarTBL.Hirecarid = OrderTBL.Hirecarid where HirecarTBL.Hirecarid in (select OrderTBL.Hirecarid from OrderTBL where uid='" + id + "')");
            while (rs.next()) {
                c.add(new OrderTBL(this.Hirecarid = rs.getInt(1), this.tongtien = rs.getDouble(2)));
            }
            con.close();
            return c;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
        public ArrayList<OrderTBL> getOrderList() {
        ArrayList<OrderTBL> c = new ArrayList<>();
        try {
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL, userDB, passDB);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(" Select  UserTBL.uid ,UserTBL.fname,UserTBL.phonenb,HirecarTBL.bienso,ngaynhan,ngaytra,tongtien from OrderTBL inner join HirecarTBL on OrderTBL.hirecarid=HirecarTBL.hirecarid\n"
                    + " Inner join UserTBL on OrderTBL.uid=UserTBL.uid");
            while (rs.next()) {
                c.add(new OrderTBL(rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getInt(7)));
            }
            con.close();
            return c;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public static void main(String[] args) {
        OrderTBL od = new OrderTBL();
        ArrayList<OrderTBL> arr = new ArrayList<>();
        arr = od.checksttOrder(2);
        for (int i = 0; i < arr.size(); i++) {
            System.out.println("1" + arr.get(i).getStatusorder());
        }
    }

}

ProjectWeb-20200327T074237Z-001/ProjectWeb/src/java/controller/LoginAction.java
package controller;

import static com.opensymphony.xwork2.Action.ERROR;
import static com.opensymphony.xwork2.Action.SUCCESS;
import com.opensymphony.xwork2.ActionContext;
import java.util.Map;
import model.UserTBLDB;
import model.UserTBL;

public class LoginAction {
     private String phonenb;
    private String pass;
    private UserTBL customer=new UserTBL();

    public String getPhonenb() {
        return phonenb;
    }

    public void setPhonenb(String phonenb) {
        this.phonenb = phonenb;
    }
    

    public String getPass() {
        return pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }
    public LoginAction() {
    }
    
    public String execute() throws Exception {
        Map<String, Object> session = ActionContext.getContext().getSession();
        UserTBL user = new UserTBL();
        UserTBLDB st = new UserTBLDB();
        if (st.getuid(phonenb) == 0) {
             session.put("mess", "Tài khoản của bạn có lẽ chưa có trên hệ thống ! !"+"\n Hoặc tài khoản và mật khậu bạn nhập đã sai !");
            return ERROR;
        }
        UserTBLDB userDB = new UserTBLDB();
        customer = userDB.getUserRight(userDB.getuid(phonenb));
        if ((customer = user.login(phonenb, pass)) != null) {
            if (customer.getUserRight() == 1) {
                session.put("CUSTOMER", customer);
                return "Admin";
            } else {
                if(customer.getLock().equals("Unlock")){
                     session.put("CUSTOMER", customer);
                     return "Customer";
                }
                else{
                    session.put("mess", "Tài khoản của bạn đã bị khóa !\n"+"\n Chúc bạn may mắn lần sau !");
                    return "lock";
                }
               
            }
        }else{
            session.put("mess", "Tài khoản của bạn có lẽ chưa có trên hệ thống ! !"+"\n Hoặc tài khoản và mật khậu bạn nhập đã sai !");
            return "mksai";
             
        }
      
    }
      public String logout() {
        Map<String, Object> session = ActionContext.getContext().getSession();
        if (session.containsKey("CUSTOMER")) {
            session.remove("CUSTOMER");
            ((org.apache.struts2.dispatcher.SessionMap) session).invalidate();
        }
        return SUCCESS;
    }
    
}

ProjectWeb-20200327T074237Z-001/ProjectWeb/src/java/controller/NaptienAction.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import static com.opensymphony.xwork2.Action.SUCCESS;
import com.opensymphony.xwork2.ActionContext;
import com.opensymphony.xwork2.ActionSupport;
import com.opensymphony.xwork2.ModelDriven;
import java.util.Map;
import model.LognoptienTBL;
import model.UserTBL;
import model.UserTBLDB;

/**
 *
 * @author letan
 */
public class NaptienAction extends ActionSupport implements ModelDriven<LognoptienTBL>  {
    LognoptienTBL nt =  new LognoptienTBL();
    
    private String phonenb;
    private int tien;
    public NaptienAction() {
    }

    public String getPhonenb() {
        return phonenb;
    }

    public void setPhonenb(String phonenb) {
        this.phonenb = phonenb;
    }

    public int getTien() {
        return tien;
    }

    public void setTien(int tien) {
        this.tien = tien;
    }
    
    
    
    public String execute() throws Exception {
       Map<String,Object> session = ActionContext.getContext().getSession();
       LognoptienTBL np = new LognoptienTBL();
       UserTBL user = new UserTBL();
       UserTBLDB userDB =new UserTBLDB();
       session.put("mess","");
       UserTBL s = (UserTBL)session.get("CUSTOMER");
        if(np.addMoney(s.getUid(),nt.getSotaikhoan(), nt.getSotien(), nt.getMapin(), nt.getPhuongthuc()) == true){
           if(user.updateTien(nt.getSotien()) == true){
               session.put("mess","Cảm ơn bạn đã tin tưởng vào website của chúng tôi.\n" +
"Bạn đã nạp tiền thành công. Trân trọng cảm ơn !");
             return SUCCESS;
         }
        }
        return ERROR;
    }
    @Override
    public LognoptienTBL getModel() {
      return nt;
    }
    
}

ProjectWeb-20200327T074237Z-001/ProjectWeb/src/java/controller/SearchResultAction.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import com.opensymphony.xwork2.ActionContext;
import com.opensymphony.xwork2.ActionSupport;
import java.util.Map;
import model.UserTBL;

/**
 *
 * @author letan
 */
public class SearchResultAction extends ActionSupport{
    
    public SearchResultAction() {
    }
    
    public String execute() throws Exception {
        Map<String, Object> session = ActionContext.getContext().getSession();
//        UserTBL s = (UserTBL) session.get("CUSTOMER");
//        if(s==null){
//            
//            return ERROR;
//        }
       return SUCCESS;
    }
    
}

ProjectWeb-20200327T074237Z-001/ProjectWeb/web/Admin.jsp
<%@page import="java.util.ArrayList"%>
<%@page import="model.UserTBL"%>
<%@page import="model.UserTBLDB"%>
<%@page contentType="text/html" pageEncoding="utf-8" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "s" %>
<jsp:useBean id="cus" class="model.UserTBLDB" scope="session"></jsp:useBean>
<jsp:useBean id="cartbl" class="model.CarTBLDB" scope="session"></jsp:useBean>
<jsp:useBean id="uid" class="model.UserTBL" scope="session"></jsp:useBean>
<jsp:setProperty name="uid" property="*"/>
<jsp:setProperty name="cartbl" property="*"/>
<jsp:useBean id="car" class="model.CarTBL" scope="session" />
<jsp:setProperty name ="car"  property="*"/>
<jsp:useBean id="hirecar" class="model.HirecarTBL" scope="session" />
<jsp:setProperty name ="hirecar"  property="*"/>
<jsp:useBean id="order" class="model.OrderTBL" scope="session" />
<jsp:setProperty name ="cus"  property="*"/>
<!doctype html>
<html>

    <head>

        <link href="styles/admin.css" rel='stylesheet' type='text/css' media="all" />

        <title>Vinoto</title>

    <div class="Head">
        <div class=logo>
            <img src="images/logo.png" width="120px" height=45px>
        </div>
        <div class="text">
            <p>${CUSTOMER.fname}</p>
            <a href="Login.jsp" style="color:yellow"><pre>   Logout</pre> </a>
        </div>

    </div>
</head>

<body>
    <div class="content-left">
        <a href="#" onclick="showtabel1();">Quản Lý User</a>
        <hr>
        <a href="#" onclick="showtabel2();">Quản Lý Giao Dịch</a>
        <hr>
        <a href="#" onclick="showtabel3();">Quản Lý Xe Đăng Ký</a>
       
    </div>
    <div class="content-right">
        <section>
            <div id="tabel1">
                <h1>User Trong Hệ Thống</h1>
                <div class="tbl-header">
                    <table cellpadding="0" cellspacing="0">
                        <thead>
                            <tr>
                                <th>PhoneNumber</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>UserRight</th>
                                <th>Address</th>
                                <th>Tiền</th> 
                                <th>Status</th>  
                                <th>      </th>  
                                <th>      </th>  
                            </tr>
                        </thead>
                    </table>
                </div>
                <div class="tbl-content">
                    <table cellpadding="0" cellspacing="0">
                        <tbody>
                            <s:forEach items="${cus.listAll()}" var="UserTBLDB">
                                <tr>
                                    <td>${UserTBLDB.phonenb}</td>
                                    <td>${UserTBLDB.fname}</td>
                                    <td>${UserTBLDB.email}</td>
                                    <td>${UserTBLDB.userRight}</td>      
                                    <td>${UserTBLDB.address}</td>
                                    <td>${UserTBLDB.tien}</td> 
                                    <td>${UserTBLDB.lock}</td>
                                    <td><button type="submit" ><a href="changeUnLock?uid=${UserTBLDB.uid}">unLock</button></a></td>
                                    <td><button type="submit"><a href="changeLock?uid=${UserTBLDB.uid}">Lock</button></a></td>
                                </tr>
                            </s:forEach>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
     <section>
            <div id="tabel2">
                <h1>Lịch sử thuê xe</h1>
                <div class="tbl-header">
                    <table cellpadding="0" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Chủ xe</th>
                                <th>Người thuê</th>
                                <th>SĐT người thuê</th>
                                <th>Biển số</th>
                                <th>Ngày thuê</th>
                                <th>Ngày trả</th>
                                <th>Tổng tiền</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                
                    <div class="tbl-content">
                        <table cellpadding="0" cellspacing="0">
                            <tbody>
                                <c:forEach items="${order.orderList}" var="p">
                                <tr>
                                    <c:forEach items="${cus.getAllChuXe(p.bienso)}" var="pp">
                                        <td>${pp.fname}</td>
                                    </c:forEach>

                                    <td>${p.fname}</td>
                                    <td>${p.phonenb}</td>
                                    <td>${p.bienso}</td>
                                    
                                    <td>${p.ngaynhan}</td>
                                    <td>${p.ngaytra}</td>
                                    <td>${p.tongtien}</td>
                                </tr>
                                </c:forEach>
                            </tbody>
                        </table>
                    </div>
                
            </div>
        </section>
        
        <section>
            <div id="tabel3">
                <h1>Quan li xe trong he thong</h1>
                <div class="tbl-header">
                    <table cellpadding="0" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Biển Số</th>
                                    <th>Số chỗ</th>
                                    <th>Hãng Xe</th>
                                    <th>Loại Nguyên Liệu</th>
                                    <th>Hộp Số</th>
                                    <th>Nơi ở hiện tại</th>
                                    <th>Tính Năng Xe</th>
                                    <th>Tiền Cho Thuê</th>
                                    <th>Trang thai</th>
                                    <th>Chức Năng</th>
                                    <th>Chức Năng</th> 
                            </tr>
                        </thead>
                    </table>
                </div>
                <div class="tbl-content">
                    <table cellpadding="0" cellspacing="0">
                        <tbody>
                            <s:forEach items="${cartbl.allbystatusAcceptCar}" var="p">
                               <tr>
                                        <td>${p.bienso}</td>
                                        <td>${p.socho}</td>
                                        <td>${p.hangxe}</td>
                                        <td>${p.loainguyenlieu}</td>
                                        <td>${p.hopso}</td>
                                        <td>${p.noiohientai}</td>
                                        <td>${p.tinhnangxe}</td>
                                        <td>${p.tienchothue}</td>
                                        <td>${p.statusAccepted}</td>
                                        <td><button><a href="acceptcar?bienso=${p.bienso}" >Accepted</a></button></td>
                                        <td><button><a href="unacceptcar?bienso=${p.bienso}">Unaccepted</a></button></td>
                                    </tr>
                            </s:forEach>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>
    <script>
        function showtabel1() {
            document.getElementById("tabel1").style.visibility = "visible";
            document.getElementById("tabel2").style.visibility = "hidden";
            document.getElementById("tabel3").style.visibility = "hidden";
        }

        function showtabel2() {
            document.getElementById("tabel1").style.visibility = "hidden";
            document.getElementById("tabel2").style.visibility = "visible";
            document.getElementById("tabel3").style.visibility = "hidden";
        }

        function showtabel3() {
            document.getElementById("tabel1").style.visibility = "hidden";
            document.getElementById("tabel2").style.visibility = "hidden";
            document.getElementById("tabel3").style.visibility = "visible";
        }
    </script>
</body>

</html>

ProjectWeb-20200327T074237Z-001/ProjectWeb/web/Error.jsp
<%@page contentType="text/html" pageEncoding="utf-8" %>
<%@ include file="/includes/header_cus.jsp" %>

<!DOCTYPE html>
<html>
        <link rel="stylesheet" href="styles/Css.css">
    <head>
       <meta charset="utf-8">
    </head>
    <body class="Naptien_body" >
   <div class="content-thongbao">
            <div class="formthongbao">
                    <label id="label_thongbao">${mess}</label>
                <img class="img_thongbao" src="images/error.png" width="200px" height=200px>
                    <br><br><br><br><br><br><br><br><br>

            </div>
        </div>
     
</body>
</html>
<%@ include file="/includes/footer.jsp" %>

ProjectWeb-20200327T074237Z-001/ProjectWeb/web/Login.jsp
<%@page contentType="text/html" pageEncoding="utf-8" %>
<%@ include file="/includes/header.jsp" %>

<!DOCTYPE html>
<html>
    <link rel="stylesheet" href="styles/Css.css">
    <head>
        <meta charset="utf-8">
    </head>
    <body class="body_login">
        <div class="login">
            <h1 id="login_h1">Login</h1>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <form action="login" method="POST">
                <input type="text" name="phonenb" placeholder="PhoneNumber" required/>
                <input type="password" name="pass" placeholder="Password" required/>
                <input type="checkbox" name ="checkRemember" ><span id="span_login">Remember me</span>
                <input type="submit" name="" value="Login">
            </form>
        </div>
    </body>
</html>
<%@ include file="/includes/footer.jsp" %>

ProjectWeb-20200327T074237Z-001/ProjectWeb/web/RutTien.jsp
<%@page contentType="text/html" pageEncoding="utf-8" %>
<%@ include file="/includes/header_cus.jsp" %>

<!DOCTYPE html>
<html>
        <link rel="stylesheet" href="styles/Css.css">
    <head>
       <meta charset="utf-8">
    </head>
    <body class="Naptien_body" >
   <div class="content-text">
            <h1 id="h1_naptien" align="center">Rút Tiền</h1>
            <div class="formcontrol">
            <form class="formnaptien" action="ruttien" method="POST">
                    <label id="label_nap_tien">Phương thức rút</label><input type="text" name="phuongthuc" value="The ATM" readonly><br>
                    <label id="label_nap_tien">Số tiền muốn rút</label><input type="text" name="tien" placeholder="Số tiền rút phải lớn hơn 50.000 đồng" ><br>
                    <label id="label_nap_tien">Số tài khoản ngân hàng</label><input type="text" name="sotaikhoan"><br>
                    <label id="label_nap_tien">Nhập lại mật khẩu</label><input type="text" name="pass" ><br>
                    <input id="Take" type="submit" value="Rút Tiền">
                </form>
            </div>
        </div>
     
</body>
</html>
<%@ include file="/includes/footer.jsp" %>